// Fixed NetrunnerDB decklists for the Core Battle Box.
//
// Each deck stores card_ids. These ids point to the records in cards.ts. The page
// loader changes the ids into the Card[] that the components use.
import type { DecklistAttributes } from './netrunnerdb';

export interface Decklist {
	id: string;
	attributes: DecklistAttributes;
	card_ids: string[];
}

export const decklistData: Decklist[] = [
	{
		id: '540f02fd-fbe3-4eae-bcff-1e0dd1a58a7a',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'topan_ormas_leader',
			name: 'Topan - Core Battle Box',
			nickname: 'Topan',
			tagline: 'Efficiency',
			notes:
				'<strong>Goal:</strong> Showcase Anarch "doomrigs" via efficient breakers and Leech.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>Topan wants to build their board as quick as possible, taking meat damage in exchange for efficiency. The deck was built with three copies of most cards so that no card is ever lost. <a href="/en/card/30034">Verbal Plasticity</a> is the MVP of this deck as you\'ll want to refill your Grip every so often. <a href="/en/card/35006">Bling</a> adds some much-needed draw but be careful -- if you host a card you can\'t play, it gets trashed!</p>\n\n<p>You want to mulligan for <a href="/en/card/30034">Verbal Plasticity</a> most games, as this allows you to churn through the deck quick. Use Topan\'s ability almost every turn to build your rig as fast as possible. Try to play out your events such as <a href="/en/card/01050">Sure Gamble</a> and <a href="/en/card/35014">Clean Getaway</a> first, then install your Hardware/Resources/Programs after.</p>\n\n<p>The classic Anarch turn currently is draw-draw-install-install. So for Topan, it might look like draw-draw, Sure Gamble, use Topan ability to install one breaker. You might go draw-Topan install-<a href="/en/card/35006">Bling</a>-<a href="/en/card/30020">Creative Commission</a> if you already have <a href="/en/card/35006">Bling</a> on the board.</p>\n\n<p>An early <a href="/en/card/30007">Fermenter</a> is great -- just let it tick up as you build your rig and cash it out later. <a href="/en/card/35007">Gourmand</a> is great to trash accessed expensive ice, or to get rid of <a href="/en/card/30040">Seamless Launch</a> or <a href="/en/card/35043">Nanomanagement</a> in the Core Battle Box matchups.</p>\n\n<p>In all, the deck has multiple copies of most cards so nothing is ever truly lost -- just take damage to build the rig and get running!</p>\n\n<p><strong>The Rig</strong></p>\n\n<p>The endgame rig is 1x <a href="/en/card/30005">Buzzsaw</a>, 1x <a href="/en/card/30025">Echelon</a>, and 1x <a href="/en/card/35009">Rising Tide</a>, with 2x <a href="/en/card/30008">Leech</a>. Extra memory via <a href="/en/card/30031">T400 Memory Diamond</a> should be for <a href="/en/card/30004">Botulus</a>, <a href="/en/card/35007">Gourmand</a>, or <a href="/en/card/30007">Fermenter</a>.</p>\n\n<p>Ideally, you\'d always want a <a href="/en/card/30007">Fermenter</a> ticking up, but this isn\'t feasible at all stages of the game. <a href="/en/card/30004">Botulus</a> is a good way to pressure early, and combined with <a href="/en/card/35007">Gourmand</a>, this allows you to thin the Corp\'s ice as they will overinstall the ice with <a href="/en/card/30004">Botulus</a> on it at times.</p>',
			tags: null,
			side_id: 'runner',
			created_at: '2026-07-14T08:57:49+00:00',
			updated_at: '2026-07-14T09:03:06+00:00',
			faction_id: 'anarch',
			card_slots: {
				bling: 3,
				botulus: 3,
				buzzsaw: 3,
				clean_getaway: 2,
				creative_commission: 3,
				docklands_pass: 1,
				echelon: 3,
				fermenter: 3,
				gourmand: 3,
				jailbreak: 3,
				leech: 3,
				rising_tide: 3,
				scrounge: 2,
				sure_gamble: 3,
				t400_memory_diamond: 3,
				topan_ormas_leader: 1,
				verbal_plasticity: 3,
				wildcat_strike: 3
			},
			num_cards: 47,
			influence_spent: 15
		},
		card_ids: [
			'bling',
			'botulus',
			'buzzsaw',
			'clean_getaway',
			'creative_commission',
			'docklands_pass',
			'echelon',
			'fermenter',
			'gourmand',
			'jailbreak',
			'leech',
			'rising_tide',
			'scrounge',
			'sure_gamble',
			't400_memory_diamond',
			'topan_ormas_leader',
			'verbal_plasticity',
			'wildcat_strike'
		]
	},
	{
		id: '8618b0f4-4ea2-4328-9fe9-ed0fa7ea83e1',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'muslihat_multifarious_marketeer',
			name: 'MuslihaT - Core Battle Box',
			nickname: 'MuslihaT',
			tagline: 'Aggression',
			notes:
				'<p><strong>Goal:</strong> Showcase how Crims can exert pressure on the Corp by forcing rezzes at inopportune times to keep their credits low.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>MuslihaT wants to hit the ground running with cards like <a href="/en/card/35017">Transfer of Wealth</a> to keep the Corp poor. There\'s a fair bit of "successful run" synergy baked into the deck, which is encouraged by <a href="/en/card/30018">Red Team</a>, such as <a href="/en/card/30015">Carmen</a>, <a href="/en/card/30008">Leech</a>, and <a href="/en/card/30011">Mutual Favor</a>.</p>\n\n<p><a href="/en/card/30018">Red Team</a> can be installed discounted via <a href="/en/card/35022">Open Market</a> -- and remember you can use it three times a turn (one per central), if it\'s feasible.</p>\n\n<p><a href="/en/card/35019">Maglectric Rapid (748 Mod)</a> is a way to force the corp to rez ice they wouldn\'t have rezzed yet, so you can get into other servers. The logic being: they can just let you into HQ if they don\'t have any agendas there. But with <a href="/en/card/35019">Maglectric Rapid (748 Mod)</a>, they now have to reconsider that. But if they rez the HQ ice, you can now run elsewhere!</p>\n\n<p><strong>The Rig</strong></p>\n\n<p>Your endgame rig will look like this: 1x <a href="/en/card/30015">Carmen</a>, 1x <a href="/en/card/35009">Rising Tide</a>, 1x <a href="/en/card/35020">Sang Kancil</a>, and 2x <a href="/en/card/30008">Leech</a>, with a <a href="/en/card/30014">Pennyshaver</a> and <a href="/en/card/30013">Docklands Pass</a> on board. This way, you can discount expensive ice via the <a href="/en/card/30008">Leech</a> counters and keep on running.</p>\n\n<p>The <a href="/en/card/30016">Marjanah</a> are meant to be early game installs if you can\'t find your <a href="/en/card/35009">Rising Tide</a> yet. When you install <a href="/en/card/35009">Rising Tide</a>, you can uninstall Marjanah -- make sure also to discard extra copies to buff <a href="/en/card/35009">Rising Tide</a>\'s strength. You can do this by overdrawing with cards like <a href="/en/card/35026">Ritual</a> and <a href="/en/card/35015">Lie Low</a>.</p>',
			tags: null,
			side_id: 'runner',
			created_at: '2026-07-14T08:57:43+00:00',
			updated_at: '2026-07-14T09:03:06+00:00',
			faction_id: 'criminal',
			card_slots: {
				carmen: 2,
				clean_getaway: 3,
				creative_commission: 3,
				docklands_pass: 1,
				jailbreak: 3,
				leech: 2,
				lie_low: 1,
				maglectric_rapid_748_mod: 2,
				maintenance_access: 3,
				marjanah: 3,
				muslihat_multifarious_marketeer: 1,
				mutual_favor: 2,
				open_market: 3,
				overclock: 2,
				pennyshaver: 2,
				red_team: 3,
				rising_tide: 1,
				ritual: 2,
				sang_kancil: 2,
				sure_gamble: 3,
				transfer_of_wealth: 3,
				tread_lightly: 1,
				wildcat_strike: 1
			},
			num_cards: 48,
			influence_spent: 15
		},
		card_ids: [
			'carmen',
			'clean_getaway',
			'creative_commission',
			'docklands_pass',
			'jailbreak',
			'leech',
			'lie_low',
			'maglectric_rapid_748_mod',
			'maintenance_access',
			'marjanah',
			'muslihat_multifarious_marketeer',
			'mutual_favor',
			'open_market',
			'overclock',
			'pennyshaver',
			'red_team',
			'rising_tide',
			'ritual',
			'sang_kancil',
			'sure_gamble',
			'transfer_of_wealth',
			'tread_lightly',
			'wildcat_strike'
		]
	},
	{
		id: '6ac61c92-81f9-4eb0-9df3-828529fd208f',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'magdalene_keino_chemutai_cryptarchitect',
			name: 'Magdalene - Core Battle Box',
			nickname: 'Magdalene',
			tagline: 'Control',
			notes:
				'<strong>Goal:</strong> Showcase the "Control Shaper" archetype by stockpiling credits and building an unbeatable rig, with some kickflips along the way.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>Magdalene is a slower runner than both of the prior entries. They want to sit back, fill up <a href="/en/card/35028">Madani</a> with various programs and install one on the Corp\'s turn and on their own turn to maximize the <a href="/en/card/30022">DZMZ Optimizer</a> value. The deck opts for a <a href="/en/card/35032">Principia</a> - <a href="/en/card/35033">“Knickknack” O’Brian</a> based economy to show new players the value of sequencing out installs and juggling memory to grind out value in the long game.</p>\n\n<p>You want to ideally draw a ton of cards during your turn, so that you can end up at 6 Grip to take advantage of <a href="/en/card/35024">Magdalene Keino-Chemutai: Cryptarchitect</a>\'s ability. You also want to find your <a href="/en/card/35028">Madani</a> and <a href="/en/card/30022">DZMZ Optimizer</a> early, so you can load up <a href="/en/card/35028">Madani</a> with programs (Ritual, draw two more cards, then last click host a lot of programs on <a href="/en/card/35028">Madani</a> is a fine play). Then, you slowly accrue value by installing programs on both the Corp and Runner turn to take advantage of the discount provided by <a href="/en/card/30022">DZMZ Optimizer</a> -- yes, it works on both turns!</p>\n\n<p>Eventually, your Madani will be filled with toolbox cards like <a href="/en/card/35029">Azimat</a>, <a href="/en/card/30004">Botulus</a>, <a href="/en/card/35030">Chromatophores</a>, <a href="/en/card/35031">Devadatta Drone</a>, and <a href="/en/card/30024">Conduit</a> so you can pull them out as the board state requires you to.</p>\n\n<p>Remember: when you install viruses such as <a href="/en/card/30004">Botulus</a> and <a href="/en/card/30007">Fermenter</a> on the end of the Corp\'s turn, these will already enter with one virus counter. Once you start your next turn, these programs will get one more virus counter, so it\'s an easy way to get into a server cheap, or to generate more money.</p>\n\n<p><a href="/en/card/35032">Principia</a> is there solely to be installed ideally for free, then sold to <a href="/en/card/35033">“Knickknack” O’Brian</a> afterwards. Don\'t shy away from installing extra copies of breakers with <a href="/en/card/30022">DZMZ Optimizer</a> discount as well, since you can sell those to <a href="/en/card/35033">“Knickknack” O’Brian</a>.</p>\n\n<p><strong>The Rig</strong></p>\n\n<p>Endgame rig is 1x <a href="/en/card/30025">Echelon</a>, 1x <a href="/en/card/35009">Rising Tide</a>, and 1x <a href="/en/card/30026">Unity</a>. You can install a second copy of either <a href="/en/card/30025">Echelon</a> or <a href="/en/card/30026">Unity</a> to bump up the strength of both breakers. All the <a href="/en/card/35032">Principia</a> copies should already have been sold to <a href="/en/card/35033">“Knickknack” O’Brian</a> to buff <a href="/en/card/35009">Rising Tide</a>.</p>\n\n<p>From here on out, you can just hammer R&amp;D with <a href="/en/card/30024">Conduit</a> to dig for agendas. It would still be nice to have a <a href="/en/card/30007">Fermenter</a> ticking down, though!</p>',
			tags: null,
			side_id: 'runner',
			created_at: '2026-07-14T08:57:36+00:00',
			updated_at: '2026-07-14T09:03:06+00:00',
			faction_id: 'shaper',
			card_slots: {
				azimat: 1,
				botulus: 1,
				chromatophores: 1,
				conduit: 1,
				creative_commission: 3,
				devadatta_drone: 1,
				docklands_pass: 1,
				dzmz_optimizer: 3,
				echelon: 2,
				fermenter: 2,
				gamedragon_pro: 1,
				knickknack_obrian: 3,
				madani: 3,
				magdalene_keino_chemutai_cryptarchitect: 1,
				mayfly: 1,
				principia: 3,
				rising_tide: 1,
				ritual: 3,
				scrounge: 3,
				sure_gamble: 3,
				telework_contract: 3,
				unity: 2,
				verbal_plasticity: 3
			},
			num_cards: 45,
			influence_spent: 14
		},
		card_ids: [
			'azimat',
			'botulus',
			'chromatophores',
			'conduit',
			'creative_commission',
			'devadatta_drone',
			'docklands_pass',
			'dzmz_optimizer',
			'echelon',
			'fermenter',
			'gamedragon_pro',
			'knickknack_obrian',
			'madani',
			'magdalene_keino_chemutai_cryptarchitect',
			'mayfly',
			'principia',
			'rising_tide',
			'ritual',
			'scrounge',
			'sure_gamble',
			'telework_contract',
			'unity',
			'verbal_plasticity'
		]
	},
	{
		id: 'ead1cbf0-44eb-4601-8af4-6860a394a108',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'leo_construction_labor_solutions',
			name: 'LEO Glacier - Core Battle Box',
			nickname: 'LEO',
			tagline: 'Glacier',
			notes:
				'<strong>Goal:</strong> Showcase how LEO can grind out wins by draining the Runner\'s money though expensive ice and upgrades.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>This LEO deck is literally just agendas, money, and protection. You want to play a slower game as you slowly build up servers with <a href="/en/card/35045">Mercia B4LL4RD</a>, and threaten "never-advance" scores on a 5/3 by using double <a href="/en/card/30040">Seamless Launch</a> + a manual advance to get five advancement counters in one turn. <a href="/en/card/30042">Manegarm Skunkworks</a> plus <a href="/en/card/30050">Anoetic Void</a> is a nasty combo, specially in Core, so your remote server is near impenetrable.</p>\n\n<p>Explaining the "SkunkVoid" Combo: when the Runner approaches the server, you can order the effects in such a way that the Runner first has to pay for <a href="/en/card/30042">Manegarm Skunkworks</a>\'s tax, then you end the run with <a href="/en/card/30050">Anoetic Void</a> afterwards.</p>\n\n<p>Slowly build up your central servers first, usually in a U-shape formation: more ice on R&amp;D and the Remote over ice on HQ, since anytime you draw an agenda, you should be jamming it in the remote anyway.</p>\n\n<p>Threaten to score out via <a href="/en/card/30040">Seamless Launch</a> at all times. This card is a prime target to recur with <a href="/en/card/30053">Spin Doctor</a> back into the deck. You need one <a href="/en/card/30040">Seamless Launch</a> to score a 4/2 (Seamless, Advance, Advance), and two <a href="/en/card/30040">Seamless Launch</a> to score a 5/3 (Seamless, Seamless, Advance).</p>\n\n<p>Once the runner passes all your ice, you may end the run by trashing your <a href="/en/card/35045">Mercia B4LL4RD</a> or <a href="/en/card/35041">Bumi 1.0</a> in the remote. They have to run it again, only to be hit with the SkunkVoid combo.</p>\n\n<p><strong>The Servers</strong></p>\n\n<p>The remote should ideally have a Bran/Palisade, an <a href="/en/card/35064">N-Pot</a>, a <a href="/en/card/35041">Bumi 1.0</a>, <a href="/en/card/35045">Mercia B4LL4RD</a>, <a href="/en/card/30050">Anoetic Void</a>, and <a href="/en/card/30042">Manegarm Skunkworks</a>. You don\'t need all of them, but a combination of these is already taxing enough.</p>\n\n<p>The centrals can have a Bran or <a href="/en/card/35064">N-Pot</a>, <a href="/en/card/30073">Tithe</a>, or <a href="/en/card/35041">Bumi 1.0</a>. <a href="/en/card/30038">Ansel 1.0</a> can go on either R&amp;D or the remote. Try to have at least one Bioroid in each server. Please remember: <a href="/en/card/35045">Mercia B4LL4RD</a> is a bioroid you can trash with the <a href="/en/card/35035">LEO Construction: Labor Solutions</a> ability!</p>',
			tags: null,
			side_id: 'corp',
			created_at: '2026-07-14T08:57:19+00:00',
			updated_at: '2026-07-14T09:03:05+00:00',
			faction_id: 'haas_bioroid',
			card_slots: {
				anoetic_void: 1,
				ansel_1_0: 1,
				bran_1_0: 3,
				bumi_1_0: 3,
				flyswatter: 2,
				hansei_review: 2,
				hedge_fund: 3,
				humanoid_resources: 3,
				leo_construction_labor_solutions: 1,
				luminal_transubstantiation: 1,
				manegarm_skunkworks: 2,
				mercia_b4ll4rd: 3,
				n_pot: 2,
				offworld_office: 3,
				palisade: 3,
				petty_cash: 2,
				predictive_planogram: 2,
				project_ingatan: 3,
				seamless_launch: 3,
				send_a_message: 2,
				spin_doctor: 3,
				tithe: 2
			},
			num_cards: 49,
			influence_spent: 15
		},
		card_ids: [
			'anoetic_void',
			'ansel_1_0',
			'bran_1_0',
			'bumi_1_0',
			'flyswatter',
			'hansei_review',
			'hedge_fund',
			'humanoid_resources',
			'leo_construction_labor_solutions',
			'luminal_transubstantiation',
			'manegarm_skunkworks',
			'mercia_b4ll4rd',
			'n_pot',
			'offworld_office',
			'palisade',
			'petty_cash',
			'predictive_planogram',
			'project_ingatan',
			'seamless_launch',
			'send_a_message',
			'spin_doctor',
			'tithe'
		]
	},
	{
		id: 'b9141c0f-3b6e-45e8-afae-044148583674',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'pt_untaian_lifes_building_blocks',
			name: 'PT Untaian Shell Game/Assets - Core Battle Box',
			nickname: 'PTU',
			tagline: 'Traps',
			notes:
				'Goal: Showcase how bluffing and mind games actively work in Netrunner through presenting interesting forks which may flatline the runner, or let you score to seven points. It may also feel like an asset spam deck, which is another unique archetype new players have yet to explore.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>Asset Spam is an archetype that involves installing as many assets as possible, usually unprotected by ice. Corps can do this because accessing the wrong card such as <a href="/en/card/35050">Byte!</a> can set the Runner back by a fair bit, so caution is still required on the Runner side.</p>\n\n<p>PT Untaian (PTU) wants to get rid of cards in HQ as fast as possible to activate its end of turn ability. Ideally, you are installing three assets on turn one and advancing one of them, taunting the Runner to check it, else it might be an agenda or a <a href="/en/card/30061">Clearinghouse</a>. You present interesting forks through cards like  <a href="/en/card/35051">Phật Gioan Baotixita</a> and <a href="/en/card/30049">Neurospike</a>, or playing the classic "Is it an <a href="/en/card/30045">Urtica Cipher</a> or <a href="/en/card/30061">Clearinghouse</a>? Game". <a href="/en/card/35050">Byte!</a> is a classic and has a punish in the form of <a href="/en/card/30068">Orbital Superiority</a> to teach Runners they should have damning reason to run last click.</p>\n\n<p>The deck can also be classified as a "Grinder" deck in that your goal is for the Runner to run out of cards in the deck, so that they cannot draw up to tank any more damage.</p>\n\n<p>Interesting lines include <a href="/en/card/35051">Phật Gioan Baotixita</a> with <a href="/en/card/30049">Neurospike</a>, which with enough counters on Phat, could be lethal.</p>\n\n<p><a href="/en/card/30045">Urtica Cipher</a> vs <a href="/en/card/30061">Clearinghouse</a> vs agenda is also one game the Runners need to play against you -- it\'s a battle of wits. They\'re more likely to access an <a href="/en/card/30045">Urtica Cipher</a> since you have three of them, but what if it\'s a <a href="/en/card/30061">Clearinghouse</a>? Just keep on advancing your cards.</p>\n\n<p>When the Runner dips in credits or cards in the Grip, you can take them out with <a href="/en/card/35078">Measured Response</a> as well. Try to keep a <a href="/en/card/35050">Byte!</a> or two in hand, or else the Runner will just run your centrals instead of contesting remotes.</p>\n\n<p><strong>The Servers</strong></p>\n\n<p>This deck is pretty free-flowing. Against Crims, you might want to protect HQ with a cheap ETR. Most times, you want a <a href="/en/card/35051">Phật Gioan Baotixita</a> cooking behind a <a href="/en/card/30074">Whitespace</a> or <a href="/en/card/35054">Semak-samun</a> then double up on it later on.</p>\n\n<p>You may build a scoring server with <a href="/en/card/35052">Empiricist</a>s, that way it makes it doubly taxing for the Runners to check your remote.</p>',
			tags: null,
			side_id: 'corp',
			created_at: '2026-07-14T08:57:01+00:00',
			updated_at: '2026-07-14T09:03:05+00:00',
			faction_id: 'jinteki',
			card_slots: {
				byte: 3,
				clearinghouse: 1,
				empiricist: 3,
				flyswatter: 1,
				hansei_review: 3,
				hedge_fund: 3,
				karuna: 2,
				longevity_serum: 1,
				measured_response: 2,
				neurospike: 1,
				orbital_superiority: 3,
				petty_cash: 3,
				phat_gioan_baotixita: 3,
				proprionegation: 3,
				pt_untaian_lifes_building_blocks: 1,
				regolith_mining_license: 2,
				semak_samun: 3,
				sericulture_expansion: 3,
				spin_doctor: 3,
				urtica_cipher: 3,
				whitespace: 3
			},
			num_cards: 49,
			influence_spent: 14
		},
		card_ids: [
			'byte',
			'clearinghouse',
			'empiricist',
			'flyswatter',
			'hansei_review',
			'hedge_fund',
			'karuna',
			'longevity_serum',
			'measured_response',
			'neurospike',
			'orbital_superiority',
			'petty_cash',
			'phat_gioan_baotixita',
			'proprionegation',
			'pt_untaian_lifes_building_blocks',
			'regolith_mining_license',
			'semak_samun',
			'sericulture_expansion',
			'spin_doctor',
			'urtica_cipher',
			'whitespace'
		]
	},

	{
		id: '54463504-6d0d-4ce2-9212-f1eb99659abf',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'nebula_talent_management_making_stars',
			name: 'Nebula Fast Advance - Core Battle Box',
			nickname: 'Nebula',
			tagline: 'Fast Advance',
			notes:
				'<strong>Goal:</strong> Showcase a more unique, combo-oriented playstyle by setting up zero remote servers and scoring every agenda out from hand.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>Fast Advance is an archetype/terminology that means you\'re scoring your agendas "out of hand". You don\'t require a pre-built server to install and advance it over two or three turns.</p>\n\n<p>This Nebula deck is a great way to showcase the flexibility of how Netrunner decks can be constructed. While most Corps require us to build remote servers to score, this deck actively only wants to protect its central servers -- and maybe some light tax for the Regolith server. When unflipped, you can use <a href="/en/card/35043">Nanomanagement</a> to get to four clicks to score a <a href="/en/card/30070">Superconducting Hub</a> or <a href="/en/card/35059">Embedded Reporting</a> out of hand via installing the agenda, then advancing it thrice. When you stay flipped, you can play <a href="/en/card/35081">Petty Cash</a> from Archives, bringing you to four clicks, and doing the same.  <a href="/en/card/35060">Next Big Thing</a> can be scored if you are flipped with double <a href="/en/card/35043">Nanomanagement</a>, which brings you to six clicks.</p>\n\n<p>You just want to keep your hand not flooded with agendas. Make money and put all of your ice on both HQ and R&amp;D and perhaps one or two on Archives to deny free <a href="/en/card/35014">Clean Getaway</a> or <a href="/en/card/35016">Maintenance Access</a> runs.</p>\n\n<p><strong>Scoring Lines</strong></p>\n\n<p>If you are on the front side of Nebula, you can use <a href="/en/card/35043">Nanomanagement</a> to get to four clicks to score out a 3/2. This costs 7 credits.</p>\n\n<p>If you are on the flipped side of Nebula, if you play <a href="/en/card/35081">Petty Cash</a> from Archives, you get a free click -- bringing you to four clicks. This means you can score a 3/2 or 3/1 with only three credits.</p>\n\n<p>If you are on the flipped side of Nebula, you can also play <a href="/en/card/35043">Nanomanagement</a> to get to five clicks (one from Nebula ability, one from Nanomanagement), then play one more <a href="/en/card/35043">Nanomanagement</a> to get to six clicks to score out <a href="/en/card/35060">Next Big Thing</a> from hand. This requires 13 credits.</p>\n\n<p><a href="/en/card/30070">Superconducting Hub</a> is a sleeper agenda here -- by having a hand size of seven or even nine, odds for the runner to access agendas from HQ can also go down, and allows us to hold several combo pieces at once.</p>\n\n<p>Remember to play at least one operation a turn to maximize Nebula\'s ability, or hold on to one operation at all times, so you can flip back in case the Runner successfully runs HQ or R&amp;D on their turn.</p>\n\n<p>If the Runner decides they want to "float" tags, that is, not detag anymore, your tag punish is <a href="/en/card/35066">IP Enforcement</a> which can turn the tide of the game.</p>\n\n<p><strong>The Servers</strong></p>\n\n<p>Just try to evenly ice both HQ and R&amp;D. <a href="/en/card/30054">Funhouse</a> is extremely taxing and <a href="/en/card/35064">N-Pot</a> gets better as the game goes on. One <a href="/en/card/35064">N-Pot</a> or <a href="/en/card/30054">Funhouse</a> on a remote for <a href="/en/card/30071">Regolith Mining License</a> isn\'t a bad idea.</p>\n\n<p>A <a href="/en/card/35082">Mahkota Langit Grid</a> each in HQ and R&amp;D is a nice way to discount your rez costs.</p>',
			tags: null,
			side_id: 'corp',
			created_at: '2026-07-14T08:57:10+00:00',
			updated_at: '2026-07-14T09:03:05+00:00',
			faction_id: 'nbn',
			card_slots: {
				bigger_picture: 1,
				doomscroll: 3,
				embedded_reporting: 3,
				flyswatter: 1,
				funhouse: 3,
				government_subsidy: 3,
				hedge_fund: 3,
				ip_enforcement: 1,
				mahkota_langit_grid: 2,
				n_pot: 3,
				nanomanagement: 3,
				nebula_talent_management_making_stars: 1,
				next_big_thing: 3,
				petty_cash: 3,
				ping: 3,
				predictive_planogram: 3,
				regolith_mining_license: 3,
				spin_doctor: 3,
				superconducting_hub: 3,
				tomorrows_headline: 1,
				whitespace: 1
			},
			num_cards: 49,
			influence_spent: 15
		},
		card_ids: [
			'bigger_picture',
			'doomscroll',
			'embedded_reporting',
			'flyswatter',
			'funhouse',
			'government_subsidy',
			'hedge_fund',
			'ip_enforcement',
			'mahkota_langit_grid',
			'n_pot',
			'nanomanagement',
			'nebula_talent_management_making_stars',
			'next_big_thing',
			'petty_cash',
			'ping',
			'predictive_planogram',
			'regolith_mining_license',
			'spin_doctor',
			'superconducting_hub',
			'tomorrows_headline',
			'whitespace'
		]
	},
	{
		id: '1077e934-c9f7-4447-834b-2bebd38b916c',
		attributes: {
			user_id: 'lunari',
			follows_basic_deckbuilding_rules: true,
			identity_card_id: 'the_zwicky_group_invisible_hands',
			name: 'Zwicky Supermodernism - Core Battle Box ',
			nickname: 'Zwicky',
			tagline: 'Supermodernism',
			notes:
				'Goal: Showcase how fast Weyland decks can close out games -- either by scoring out, or outright flatlining the Runner.</p>\n\n<p><strong>Gameplan</strong></p>\n\n<p>Supermodernism is a tried-and-tested archetype. Have cheap End the Run ice such as Kessleroid, a natsy Sentry in Biawak to punish mid-game contests without killers installed, and a way to flatline the Runner via Measured Response if they interact with your board.</p>\n\n<p>Ideally, you want to make money in the first turn while protecting your central servers with <a href="/en/card/35075">Kessleroid</a> and <a href="/en/card/35079">Flyswatter</a>. You can also opt to ice HQ or R&amp;D, then build a remote with ice + <a href="/en/card/35072">Anthill Excavation Contract</a> or <a href="/en/card/35039">Humanoid Resources</a>.</p>\n\n<p>Once you have some credits but before the Runner is fully set up, you want to start pushing out agendas even behind a single piece of ice in the remote. Once you or the Runner get to four points, you can now start taxing them out with Bran 1.0 into <a href="/en/card/35078">Measured Response</a>. </p>\n\n<p>A surprise <a href="/en/card/35074">Biawak</a> from an early <a href="/en/card/35070">Greenmail</a> score will keep Runners honest -- they cannot check your remote unless they already have their killer on board.</p>\n\n<p><strong>The Servers</strong></p>\n\n<p>You want some form of light protection on centrals like <a href="/en/card/35075">Kessleroid</a> or maybe even <a href="/en/card/35076">Syailendra</a> which is an annoying break, while the remote has a <a href="/en/card/35074">Biawak</a>, Bran 1.0, and <a href="/en/card/30072">Palisade</a>. Extra <a href="/en/card/35074">Biawak</a>s can also go on centrals.</p>',
			tags: null,
			side_id: 'corp',
			created_at: '2026-07-14T08:57:26+00:00',
			updated_at: '2026-07-14T09:03:05+00:00',
			faction_id: 'weyland_consortium',
			card_slots: {
				above_the_law: 1,
				anthill_excavation_contract: 3,
				biawak: 3,
				bran_1_0: 3,
				flyswatter: 2,
				government_subsidy: 3,
				greenmail: 3,
				hedge_fund: 3,
				humanoid_resources: 3,
				kessleroid: 3,
				key_performance_indicators: 3,
				measured_response: 3,
				off_the_books: 3,
				offworld_office: 3,
				palisade: 1,
				petty_cash: 3,
				send_a_message: 1,
				spin_doctor: 3,
				syailendra: 2,
				the_zwicky_group_invisible_hands: 1
			},
			num_cards: 49,
			influence_spent: 15
		},
		card_ids: [
			'above_the_law',
			'anthill_excavation_contract',
			'biawak',
			'bran_1_0',
			'flyswatter',
			'government_subsidy',
			'greenmail',
			'hedge_fund',
			'humanoid_resources',
			'kessleroid',
			'key_performance_indicators',
			'measured_response',
			'off_the_books',
			'offworld_office',
			'palisade',
			'petty_cash',
			'send_a_message',
			'spin_doctor',
			'syailendra',
			'the_zwicky_group_invisible_hands'
		]
	}
];
